name: flutter_gherkin
description: A Gherkin / Cucumber parser and test runner for Dart and Flutter
version: 0.0.2
author: Jon Samwell <jonsamwell@gmail.com>
homepage: https://github.com/jonsamwell/flutter_gherkin

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.6.2
  glob: ^1.1.7
  test: ^1.3.0
  matcher: 0.12.3+1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

dev_dependencies:

flutter:
