name: flutter_gherkin
description: A Gherkin / Cucumber parser and test runner for Dart and Flutter
version: 1.2.0
homepage: https://github.com/jonsamwell/flutter_gherkin

environment:
  sdk: '>=2.12.3 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  gherkin: ^2.0.0
  # gherkin:
    # path: ../dart_gherkin
  # gherkin:
  #   git:
  #     url: https://github.com/jonsamwell/dart_gherkin.git
  #     ref: f0b3f955191b53a78075ed2c9387ea8bee12f111

dependency_overrides:
  crypto: ^3.0.0 # flutter_driver still depends on 2.1.5 :-(
  convert: ^3.0.0 # flutter_driver still depends on >=2.0.0 :-(
  test: ^1.16.5 # gherkin still depends on 1.16.8 :-(
  test_api: ^0.3.0 # flutter_test still depends on 0.2.19 :-(

dev_dependencies:
  integration_test:
    sdk: flutter
  test: ^1.16.5
  meta: ^1.3.0 
  pedantic: ^1.11.0
  glob: ^2.0.1
  source_gen: ^1.0.0
  build: ^2.0.1
  build_config: ^1.0.0

flutter:
