name: example_with_integration_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  json_serializable: ^3.5.1
  json_annotation: ^3.1.1
  rxdart: ^0.25.0
  shared_preferences: ^0.5.12+4
  uuid: ^2.2.2
  flutter_simple_dependency_injection: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test: ^1.0.0
  build_runner: ^1.10.11
  flutter_gherkin:
    path: ../

flutter:

  uses-material-design: true