name: example_with_integration_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test: ^1.0.0
  build_runner: ^1.10.11
  flutter_gherkin:
    path: ../

flutter:

  uses-material-design: true